# To expose the SUPABASE_SERVICE_ROLE_KEY to the Deno runtime,
# you must explicitly list it here.
# The SUPABASE_URL is automatically included.
import_map = "../import_map.json"
envs = ["SUPABASE_SERVICE_ROLE_KEY"]